---
# defaults file for infra_server_kvm_cloud_create

vm_name: centos8-lab1
vm_hostname: centos8-stream.lab.local
vm_osinfo_id: http://centos.org/centos-stream/8
vm_cloud_image: CentOS-Stream-GenericCloud-8-20210603.0.x86_64.qcow
vm_mem: 4096
vm_mem_current: 4096
vm_cpu: 1
vm_disks: [
  { device: "vda", size: 20G, bootable: true }
]
vm_mac_prefix: "bc:ae:80"
vm_interfaces: []
vm_default_partition: { device: "vda", part_num: 1, size: 10, unit: GiB }
vm_default_filesystem: { device: "vda1", mountpoint: "/", fstype: "xfs", type: "standard" }
vm_partitions: []
vm_volume_groups: []
vm_logical_volumes: []
vm_filesystems: []
