galaxy_info:
  author: Petros Petrou
  description: Provisions Fedora CoreOS using the QEMU Provided Image
  company: NA

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: license (LGPL)

  min_ansible_version: 2.4

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
   - name: Fedora
     versions:
     - all
   - name: EL
     versions:
     - 7
     - 8

  galaxy_tags:
    - KVM
    - CoreOS

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
