$ANSIBLE_VAULT;1.1;AES256
66396237323662646364363039653539356234323938323964373761373163326434396239643534
6463666138333334383834363634323066393931383462310a306163353438386130646532616130
61636464396264343133396537653037373166366530303437326132393134343434366636306633
3464346636616663350a343734313864333331353634316631373433323331343066363462313334
33343461323864316433666561363762306565303536383338663032663838303432663335333362
66636561616330333463633531393936666462613534613961613836366261623437663432386536
62653862663966666239633533636338323061656235393636356137656634326536646538633662
66306130643933313235393037323031643130343663386264663839663436613934613665666466
31383363653037666361353665653239386631393039333066373062623432313839643838636465
35363061313239623631303830326331323833303330643763313533343233343065643135303164
393037613561646164633132376264653038
