---
# defaults file for infra_server_kvm_noos_create

vm_name: rhel7-dev-01
vm_osinfo_id: http://redhat.com/rhel/7.6
vm_mem: 4096
vm_mem_current: 4096
vm_cpu: 2
vm_disks:
  - { device: "vda", format: "qcow2", size: "10G", bootable: true }
vm_mac_prefix: "bc:ae:80"
vm_interfaces: []
