---
- hosts: hypervisor
  vars_files:
    - ../../../vars/snapshot_vars.yml

  vars_prompt:
    - name: prefix_snapshot_name
      prompt: "Prefix Snapshot Name"
      private: no

  tasks:

    # List all KVMS
    - name: list all VMs
      virt:
        command: list_vms
      register: reg_all_vms

    # Check all KVMs are shutdown
    - name: Check all KVMs are shutdown
      virt:
        name: "{{ item }}"
        command: status
      register: reg_vm_status
      with_items:
        - "{{ reg_all_vms.list_vms }}"
      failed_when:
        - reg_vm_status.status in ['running','crashed','paused']

    # Revert snapshot
    - name: Revert snapshots
      command: virsh -c {{ qemu_conn }} snapshot-revert --domain {{ item }} --snapshotname {{ prefix_snapshot_name }}.{{ item }}
      with_items:
        - "{{ reg_all_vms.list_vms }}"
